### PR TITLE
Use constant time compare from subtle

### PR DESCRIPTION
**Pull request by sporkmonger**
There's no need for the custom function

### CODE REVIEW

**Comment by sporkmonger** [comment]
Apply #1 first to clean up diff.

**Review by opencoff — COMMENTED** [review]
The reason for the custom function is to avoid memory allocation during string to []byte conversion. The stdlib subtle requires []byte slices. The input I have is string. 

There is talk in the golang-dev team to make the conversion zero cost in a future version of golang.

**Comment by sporkmonger** [comment]
Gotcha, though I guess I'm not sure why that would be a concern in this context?

**Comment by opencoff** [comment]
Good question :-) My original use case was in an embedded context that had to work under resource constraints; so I was minimizing memory allocation as much as possible. I suppose for the larger community use - subtle.Compare() is a better choice.

**Review by opencoff — APPROVED** [review]

**Pull request merged**
