### PR TITLE
Allow Server to be marshaled to string

### PR DESCRIPTION
**Pull request by mcrute**
In certain cases the client and server are not able to maintain a connection through the entire authentication process and the Server instance is destroyed which breaks the authentication flow. One example of this is a client that is using SRP over HTTP(S) which requires a minimum of two round trips to authenticate the user.

This change introduces a `Server.Marshal` and `UnmarshalServer` function that allows the server side of the transaction to marshal its `Server` instance for storage and later use when the client returns with their authentication data.

### CODE REVIEW

**Comment by mcrute** [comment]
Just checking up on this... are there any changes that need to be made or is this in a state that you'd be willing to merge? @opencoff

**Comment by mcrute** [comment]
Rebased this PR off of the latest changes. Can this be merged?

**Comment by opencoff** [comment]
Merged; and updated to latest golang/x/crypto.

**Comment by mcrute** [comment]
Thank you!

**Pull request merged**
